language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
install: 
  - pip install -rrequirements.txt
  - python setup.py install
  - pip install coveralls
script: 
  - python setup.py test
  - coverage run --source=hep-ipython-tools setup.py test
after:
  - coveralls
